#!/usr/bin/env bash

bench "lzip --keep --decompress --force lzlib-1.10.tar.lz" \
    "lzip --keep --decompress --force gmp-6.1.2.tar.lz" \
    "lzip --keep --force lzlib-1.10.tar" \
    "lzip --keep --force gmp-6.1.2.tar"
