jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-haskell@v1"
        with:
          cabal-version: "3.0"
          ghc-version: "8.8.1"
      - name: "Install dependencies"
        run: |
          cabal update
          cabal build --enable-tests --only-dependencies
      - name: Build
        run: "cabal build"
      - name: "Get test data"
        run: |
          sudo apt install lzip
          make -j
      - name: Tests
        run: "cabal test"
name: "Haskell CI"
on:
  - push
