name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.1'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal build lzlib-test --only-dependencies
        make -j
    - name: Build
      run: |
        cabal build
    - name: Run tests
      run: |
        cabal test
